services:
  iam-service:
    image: registry.gitlab.com/healthcare5314327/microservices/iam-service:0.0.0
    ports:
      - "8080:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgresql-sgp1-01273-do-user-23760201-0.g.db.ondigitalocean.com:25060/iam-db
      SPRING_DATASOURCE_USERNAME: doadmin
    secrets:
      - db_password
    entrypoint:
      - sh
      - -c
      - >
        export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password) &&
        exec java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
        -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom
        -jar app.jar
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - microservices-network

  # patient-service:
  #   image: registry.gitlab.com/healthcare5314327/microservices/patient-service:latest
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgresql-sgp1-01273-do-user-23760201-0.g.db.ondigitalocean.com:25060/patient-db
  #     SPRING_DATASOURCE_USERNAME: doadmin
  #   secrets:
  #     - db_password
  #   entrypoint:
  #     - sh
  #     - -c
  #     - >
  #       export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password) &&
  #       exec java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
  #       -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom
  #       -jar app.jar
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - microservices-network

  # testorder-service:
  #   image: registry.gitlab.com/healthcare5314327/microservices/testorder-service:latest
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgresql-sgp1-01273-do-user-23760201-0.g.db.ondigitalocean.com:25060/testorder-db
  #     SPRING_DATASOURCE_USERNAME: doadmin
  #   secrets:
  #     - db_password
  #   entrypoint:
  #     - sh
  #     - -c
  #     - >
  #       export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password) &&
  #       exec java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
  #       -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom
  #       -jar app.jar
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - microservices-network

networks:
  microservices-network:
    driver: overlay

secrets:
  db_password:
    external: true
