services:
  iam-service:
    image: registry.gitlab.com/healthcare5314327/microservices/iam-service:15-jul-1524
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: when-authorized
      LOGGING_LEVEL_ROOT: WARN
    secrets:
      - db_password
      - db_url
      - db_username
    entrypoint:
      - sh
      - -c
      - >
        export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password) &&
        export SPRING_DATASOURCE_URL=$$(cat /run/secrets/db_url) &&
        export SPRING_DATASOURCE_USERNAME=$$(cat /run/secrets/db_username) &&
        exec java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
        -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom
        -jar app.jar
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 120s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 120s
        order: stop-first
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 768M
    networks:
      - microservices-network
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/iam/actuator/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 120s

  patient-service:
    image: registry.gitlab.com/healthcare5314327/microservices/patient-service:15-jul-1526
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: production
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: when-authorized
      LOGGING_LEVEL_ROOT: WARN
    secrets:
      - db_password
      - patient_db_url
      - db_username
    entrypoint:
      - sh
      - -c
      - >
        export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password) &&
        export SPRING_DATASOURCE_URL=$$(cat /run/secrets/patient_db_url) &&
        export SPRING_DATASOURCE_USERNAME=$$(cat /run/secrets/db_username) &&
        exec java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
        -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom
        -jar app.jar
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 120s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 120s
        order: stop-first
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 768M
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/patient/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # testorder-service:
  #   image: registry.gitlab.com/healthcare5314327/microservices/testorder-service:latest
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: production
  #     MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics
  #     MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: when-authorized
  #     LOGGING_LEVEL_ROOT: WARN
  #   secrets:
  #     - db_password
  #     - testorder_db_url
  #     - db_username
  #   entrypoint:
  #     - sh
  #     - -c
  #     - >
  #       export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password) &&
  #       export SPRING_DATASOURCE_URL=$$(cat /run/secrets/testorder_db_url) &&
  #       export SPRING_DATASOURCE_USERNAME=$$(cat /run/secrets/db_username) &&
  #       exec java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
  #       -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom
  #       -jar app.jar
  #   deploy:
  #     replicas: 2
  #     restart_policy:
  #       condition: on-failure
  #       delay: 10s
  #       max_attempts: 3
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
  #       failure_action: rollback
  #       monitor: 120s
  #       order: start-first
  #     rollback_config:
  #       parallelism: 1
  #       delay: 10s
  #       failure_action: pause
  #       monitor: 120s
  #       order: stop-first
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 1G
  #       reservations:
  #         cpus: '0.25'
  #         memory: 768M
  #   networks:
  #     - microservices-network
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/testorder/actuator/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 120s

networks:
  microservices-network:
    driver: overlay
    attachable: true

secrets:
  db_password:
    external: true
  db_url:
    external: true
  patient_db_url:
    external: true
  testorder_db_url:
    external: true
  db_username:
    external: true
