services:
  nginx-proxy:
    image: nginx:1.27.0-alpine
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/var/www/html:ro
      - ./nginx/wait-for-dns.sh:/wait-for-dns.sh:ro
    entrypoint: ["sh", "/wait-for-dns.sh"]
    networks:
      - microservices-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  iam-service:
    image: registry.gitlab.com/healthcare5314327/microservices/iam-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: production
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      LOGGING_LEVEL_ROOT: WARN
    secrets:
      - db_password
      - db_url
      - db_username
      - smtp_username
      - smtp_password
    entrypoint: ["sh", "/scripts/start-iam.sh"]
    volumes:
      - ./scripts/start-iam.sh:/scripts/start-iam.sh:ro
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 120s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 120s
        order: stop-first
      resources:
        limits:
          cpus: '1.25'
          memory: 896M
        reservations:
          cpus: '0.5'
          memory: 640M
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/iam/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  patient-service:
    image: registry.gitlab.com/healthcare5314327/microservices/patient-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: production
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      LOGGING_LEVEL_ROOT: WARN
    secrets:
      - db_password
      - patient_db_url
      - db_username
    entrypoint: ["sh", "/scripts/start-patient.sh"]
    volumes:
      - ./scripts/start-patient.sh:/scripts/start-patient.sh:ro
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 120s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 120s
        order: stop-first
      resources:
        limits:
          cpus: '0.25'
          memory: 1.25G
        reservations:
          cpus: '0.2'
          memory: 896M
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/patient/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  testorder-service:
    image: registry.gitlab.com/healthcare5314327/microservices/testorder-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: production
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      LOGGING_LEVEL_ROOT: WARN
    secrets:
      - db_password
      - testorder_db_url
      - db_username
    entrypoint: ["sh", "/scripts/start-testorder.sh"]
    volumes:
      - ./scripts/start-testorder.sh:/scripts/start-testorder.sh:ro
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 120s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 120s
        order: stop-first
      resources:
        limits:
          cpus: '0.375'
          memory: 1.25G
        reservations:
          cpus: '0.25'
          memory: 896M
    networks:
      - microservices-network
    healthcheck:
      # test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/testorder/actuator/health"]
      test: ["CMD", "true"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

networks:
  microservices-network:
    driver: overlay
    attachable: true

secrets:
  db_password:
    external: true
  db_url:
    external: true
  patient_db_url:
    external: true
  testorder_db_url:
    external: true
  db_username:
    external: true
  smtp_username:
    external: true
  smtp_password:
    external: true
  mongodb_uri:
    external: true
  rabbitmq_username:
    external: true
  rabbitmq_password:
    external: true
