services:
  iam-service:
    image: registry.gitlab.com/healthcare5314327/microservices/iam-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      LOGGING_LEVEL_ROOT: WARN
    secrets:
      - db_password
      - db_url
      - db_username
      - smtp_username
      - smtp_password 
    entrypoint:
      - sh
      - -c
      - >
        export MANAGEMENT_HEALTH_MAIL_ENABLED=false &&
        export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password) &&
        export SPRING_DATASOURCE_URL=$$(cat /run/secrets/db_url) &&
        export SPRING_DATASOURCE_USERNAME=$$(cat /run/secrets/db_username) &&
        export SPRING_MAIL_USERNAME=$$(cat /run/secrets/smtp_username) &&
        export SPRING_MAIL_PASSWORD=$$(cat /run/secrets/smtp_password) &&
        exec java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
        -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom
        -jar app.jar
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 120s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 120s
        order: stop-first
      resources:
        limits:
          cpus: '1.25'
          memory: 896M
        reservations:
          cpus: '0.5'
          memory: 640M
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/iam/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  patient-service:
    image: registry.gitlab.com/healthcare5314327/microservices/patient-service:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: production
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      LOGGING_LEVEL_ROOT: WARN
    secrets:
      - db_password
      - patient_db_url
      - db_username
    entrypoint:
      - sh
      - -c
      - >
        export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password) &&
        export SPRING_DATASOURCE_URL=$$(cat /run/secrets/patient_db_url) &&
        export SPRING_DATASOURCE_USERNAME=$$(cat /run/secrets/db_username) &&
        exec java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
        -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom
        -jar app.jar
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 120s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 120s
        order: stop-first
      resources:
        limits:
          cpus: '0.25'
          memory: 1.25G
        reservations:
          cpus: '0.2'
          memory: 896M
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/patient/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  testorder-service:
    image: registry.gitlab.com/healthcare5314327/microservices/testorder-service:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: production
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      LOGGING_LEVEL_ROOT: WARN
    secrets:
      - db_password
      - testorder_db_url
      - db_username
    entrypoint:
      - sh
      - -c
      - >
        export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password) &&
        export SPRING_DATASOURCE_URL=$$(cat /run/secrets/testorder_db_url) &&
        export SPRING_DATASOURCE_USERNAME=$$(cat /run/secrets/db_username) &&
        exec java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
        -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom
        -jar app.jar
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 120s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 120s
        order: stop-first
      resources:
        limits:
          cpus: '0.375'
          memory: 1.25G
        reservations:
          cpus: '0.25'
          memory: 896M
    networks:
      - microservices-network
    healthcheck:
      # test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/testorder/actuator/health"]
      test: ["CMD", "true"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

networks:
  microservices-network:
    driver: overlay
    attachable: true

secrets:
  db_password:
    external: true
  db_url:
    external: true
  patient_db_url:
    external: true
  testorder_db_url:
    external: true
  db_username:
    external: true
  smtp_username:
    external: true
  smtp_password:
    external: true
