# Server config
ssh_port:
server_user: ""
server_user_password: ""

# GitLab credential
gitlab_token: ""

# Cloudflare
cloudflare_api_token: ""
domain_name: ""

# PostgreSQL Database credentials and connection strings
db_password: ""
db_username: ""
iam_db_url: ""
patient_db_url: ""
testorder_db_url: ""

# MongoDB credientials
mongodb_uri: ""

# RabbitMQ credentials
rabbitmq_host: ""
rabbitmq_port:
rabbitmq_username: ""
rabbitmq_password: ""
rabbitmq_vhost: ""

# OPT
mailtrap_api_token: "<mailtrap-api-token"
mailtrap_sender_email: "<email"
mailtrap_sender_name: "<name>"

# JWT secret
jwt_secret: ""
