---
- name: Provision All Nodes
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - vars/secrets.yml

  pre_tasks:
    - name: Stop and mask automatic update services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        masked: yes
      loop:
        - unattended-upgrades
        - apt-daily.service
        - apt-daily.timer
        - apt-daily-upgrade.service
        - apt-daily-upgrade.timer
      ignore_errors: true

    - name: Wait a moment for processes to fully stop
      ansible.builtin.pause:
        seconds: 5

    - name: Remove any stale lock files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/cache/apt/archives/lock
      ignore_errors: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        lock_timeout: 300
      register: apt_update
      retries: 3
      delay: 10
      until: apt_update is succeeded

  tasks:
    - name: Install prerequisites and CLI tools
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - btop
          - tree
          - bat
          - net-tools
          - neofetch
        state: present
        lock_timeout: 300
      register: apt_prereqs
      retries: 3
      delay: 10
      until: apt_prereqs is succeeded

    - name: Symlink batcat to bat
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Set timezone to Asia/Ho_Chi_Minh
      ansible.builtin.timezone:
        name: Asia/Ho_Chi_Minh

    - name: Create non-root user
      ansible.builtin.user:
        name: "{{ server_user }}"
        state: present
        shell: /bin/bash
        create_home: yes
        groups: sudo
        append: yes
        password: "{{ server_user_password | password_hash('sha512') }}"

    - name: Create .ssh directory for the user
      ansible.builtin.file:
        path: "/home/{{ server_user }}/.ssh"
        state: directory
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: "0700"

    - name: Copy root's authorized_keys to user
      ansible.builtin.copy:
        src: /root/.ssh/authorized_keys
        dest: "/home/{{ server_user }}/.ssh/authorized_keys"
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: "0600"
        remote_src: yes

    - name: Download Starship installation script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_install.sh
        mode: "0755"

    - name: Install Starship
      ansible.builtin.shell: /tmp/starship_install.sh --yes
      args:
        creates: /usr/local/bin/starship

    - name: Add Starship to bash profile for all users
      ansible.builtin.blockinfile:
        path: /etc/profile.d/starship.sh
        create: yes
        mode: "0755"
        block: |
          # Initialize Starship prompt
          if command -v starship >/dev/null 2>&1; then
            eval "$(starship init bash)"
          fi

    - name: Add Helix PPA
      ansible.builtin.apt_repository:
        repo: ppa:maveonair/helix-editor
        state: present

    - name: Install Helix
      ansible.builtin.apt:
        name: helix
        state: present
        update_cache: yes

    - name: Disable ssh.socket
      ansible.builtin.systemd:
        name: ssh.socket
        state: stopped
        enabled: no

    - name: Change SSH port to {{ ssh_port }}
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Port"
        line: "Port {{ ssh_port }}"
        backup: yes

    - name: Disable password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"

    - name: Disable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"

    - name: Enable PAM
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?UsePAM"
        line: "UsePAM yes"

    - name: Validate SSH config
      ansible.builtin.command: sshd -t

    - name: Reload SSH service
      ansible.builtin.systemd:
        name: ssh
        state: restarted

    - name: Set UFW default incoming policy to deny
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Set UFW default outgoing policy to allow
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Limit SSH (custom port)
      community.general.ufw:
        rule: limit
        port: "{{ ssh_port }}"
        proto: tcp

    - name: Allow HTTP (port 80)
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Allow Docker Swarm cluster management (TCP 2377)
      community.general.ufw:
        rule: allow
        port: "2377"
        proto: tcp

    - name: Allow Docker Swarm node communication (TCP 7946)
      community.general.ufw:
        rule: allow
        port: "7946"
        proto: tcp

    - name: Allow Docker Swarm node communication (UDP 7946)
      community.general.ufw:
        rule: allow
        port: "7946"
        proto: udp

    - name: Allow Docker Swarm overlay network (UDP 4789)
      community.general.ufw:
        rule: allow
        port: "4789"
        proto: udp

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Create microservices directory
      ansible.builtin.file:
        path: /opt/microservices
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy swarm directory to /opt/microservices
      ansible.builtin.copy:
        src: ../swarm/
        dest: /opt/microservices/
        owner: root
        group: root
        mode: preserve
        backup: yes

    - name: Make shell scripts executable
      ansible.builtin.file:
        path: "/opt/microservices/scripts/{{ item }}"
        mode: "0755"
      loop:
        - cleanup.sh
        - deploy.sh

    - name: Create directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: "0644"

    - name: Add Docker GPG key
      ansible.builtin.shell: |
        gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
        chmod 644 /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
        state: present
        filename: docker

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
        lock_timeout: 300
      register: apt_docker
      retries: 3
      delay: 10
      until: apt_docker is succeeded

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ server_user }}"
        groups: docker
        append: yes

    - name: Login to GitLab Container Registry
      ansible.builtin.shell: |
        echo "{{ gitlab_token }}" | docker login registry.gitlab.com -u "{{ gitlab_token }}" --password-stdin
      no_log: true
